# Generated by Django 4.2.1 on 2023-06-07 09:56

import first_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageCarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Главная надпись на каруселе', max_length=100, verbose_name='Главная надпись на каруселе')),
                ('description', models.CharField(blank=True, default='Краткое описание карусели', max_length=100, verbose_name='Краткое описание карусели')),
                ('image', models.ImageField(default='carousel/default/default.png', upload_to=first_app.models.carouselitem_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя работника(фио)')),
                ('place', models.CharField(max_length=100, verbose_name='Должность')),
                ('person_image', models.ImageField(default='persons/default/default.png', upload_to=first_app.models.person_image_path)),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название услуги')),
                ('short_descr', models.CharField(default='Empty', max_length=100, verbose_name='Краткое описание услуги')),
                ('descr', models.TextField(default='Empty', verbose_name='Описание услуги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название проекта')),
                ('full_descr', models.TextField(blank=True, default=None, null=True, verbose_name='Полное описание проекта')),
                ('short_descr', models.CharField(default='Empty', max_length=100, verbose_name='Краткое описание проекта')),
                ('descr', models.TextField(default='Empty', verbose_name='Описание проекта')),
                ('images', models.ManyToManyField(default=None, to='first_app.image', verbose_name='Изображение проекта')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='first_app.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
