# Generated by Django 4.2.1 on 2023-06-25 08:26

import first_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Заголовок новости')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Описание новости')),
            ],
        ),
        migrations.AlterModelOptions(
            name='homepagecarouselitem',
            options={'verbose_name': 'Карусель', 'verbose_name_plural': 'Карусели'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterField(
            model_name='homepagecarouselitem',
            name='image',
            field=models.ImageField(default='carousel/default/default.png', upload_to=first_app.models.carouselitem_image_path, verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='homepagecarouselitem',
            name='news',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='first_app.news', verbose_name='Новость'),
        ),
    ]
