# Generated by Django 4.2.1 on 2023-06-26 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_news_alter_homepagecarouselitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
