# Generated by Django 4.2.1 on 2023-06-07 09:19

from django.db import migrations, models
import django.db.models.deletion
import second_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Svg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('logo', models.FileField(upload_to='svgs/', verbose_name='иконка')),
            ],
            options={
                'verbose_name': 'Иконка',
                'verbose_name_plural': 'Иконки',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Услуга', max_length=100, verbose_name='Название услуги')),
                ('second_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название вверху')),
                ('description', models.TextField(blank=True, default='Описание', verbose_name='Описание услуги')),
                ('image', models.ImageField(blank=True, default='media/images/default.png', null=True, upload_to=second_app.models.service_image_path, verbose_name='Изображение услуги')),
                ('logo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='second_app.svg', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('descr', models.TextField(blank=True, max_length=200, verbose_name='Описание')),
                ('logo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='second_app.svg', verbose_name='Икона')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
            },
        ),
    ]
